name: mot_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  graphic: ^2.5.1
  http: ^1.3.0
  equatable: ^2.0.7
  provider: ^6.1.2
  syncfusion_flutter_charts: ^28.2.7
  intl: ^0.20.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
